# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applydatetime', models.DateTimeField()),
                ('date', models.DateField()),
                ('time', models.IntegerField()),
                ('num', models.IntegerField()),
                ('com', models.CharField(blank=True, max_length=30, null=True)),
                ('usereason', models.CharField(max_length=100)),
                ('stat', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('pwd', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=15)),
                ('mail', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_admin', serialize=False, to='hds.User')),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_br', to='hds.User'),
        ),
        migrations.AlterUniqueTogether(
            name='borrowrecord',
            unique_together=set([('date', 'time', 'user')]),
        ),
    ]
